language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    - stage: build
      jdk: openjdk8
      script: mvn clean test
      branches:
        except:
          - master